version: '3'
services:
  api:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
